added insertion sort
coderobe/sorting pull request #3
Opened 2018-10-28 17:25 UTC by chaserdoe

2018-10-28 17:41 UTC, coderobe commented
kann das evtl auch mit algo::swap arbeiten?

2018-10-28 17:41 UTC, chaserdoe commented
eher schwierig...

2018-10-28 17:43 UTC, coderobe commented
hmm, ich schau mal ob ich den swap delay in traceableatom implementiert bekomme; dann muss sowas die delaymethoden nicht hardcoden

2018-10-28 19:11 UTC, coderobe requested changes
müsstest die mergekonflikte regeln und die benannten zeilen rausschmeißen, dann :ok_hand:

2018-10-28 19:11 UTC, coderobe commented on src/algo.cpp
> +          this_thread::sleep_for(chrono::microseconds(delay));
das kann jetzt weg

2018-10-28 19:11 UTC, coderobe commented on src/algo.cpp
> +        if(!running) return;
das kann auch raus

2018-10-29 14:44 UTC, coderobe approved these changes

2018-10-29 14:44 UTC, merged